### ISSUE TITLE
测试异常被吃掉了

### ISSUE THREAD

**Issue by ngot** [xicilion/fibjs#180]
测试文件 t.js：

```js
const test = require("test");
test.setup();

describe('t', () => {
  it('test', () => assert.equal(1, 2));
});

test.run(console.DEBUG);
```

执行测试：

```shell
fibjs t.js
echo $?
```

结果：

```
Error: expected 1 to equal 2
    at it (t.js:5:27)
    at t.js:8:6
    1) test

  × 1 of 1 tests failed (1ms)

0
```

由于，assert的异常被测试框架给吃掉了，导致外部执行命令拿不到本次测试的结果。导致了 travis ci 这样的平台无法得知 ci 的结果。

在测试中，错误，应该不需要吃掉吧。

**Comment by ngot** [comment]
@xicilion 这个求看一下

**Comment by xicilion** [comment]
test.run 只会抛出错误，不会返回错误给 process。
如果需要 process 知道错误，需要 process.exit(test.run());

**Comment by ngot** [comment]
Get!
